server:
  port: 7777
  undertow:
    io-threads: 8 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 200 # 阻塞任务线程池,undertow会从这个线程池中取得线程,默认值是IO线程数*8,最大值400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024 # 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)

spring:
  application:
    name: auth-server
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池最大空闲连接
        max-wait: 30ms # 连接池最大阻塞等待时间
        min-idle: 1 # 连接池中的最小空闲连接

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
