server:
  port: 7001
  undertow:
    io-threads: 2         #设置IO线程数,默认设置每个CPU核心一个线程
    worker-threads: 50    #阻塞任务线程池,默认值是IO线程数*8
    buffer-size: 1024     #每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true  #是否分配的直接内存(NIO直接分配的堆外内存)

spring:
  application:
    name: baseuser-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yhb_code?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50        #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      minimum-idle: 10             #连接池最小连接数
      connection-timeout: 30000    #连接超时时间 --30秒
      idle-timeout: 60000          #连接空闲时间 --1分钟
      max-lifetime: 300000         #连接生命周期，建议设置比数据库超时时长少30秒以上 --5分钟
      validation-timeout: 3000
      login-timeout: 5
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.server.cloud.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #将执行的sql打印出来，在开发或测试的时候可以用